version: '3.1'

services:
  apivendas-db:
    container_name: apivendas-db
    image: postgres
    restart: always
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apivendas
    ports:
      - 5434:5432

  redis:
    image: 'bitname/redis:latest'
    container_name: apivendas-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
